services:
  - type: web
    name: rasa-backend
    env: python
    buildCommand: "rasa train"
    startCommand: "rasa run --enable-api --cors '*' --port 10000"
    plan: free
    envVars:
      - key: RASA_ENV
        value: production

  - type: web
    name: rasa-actions
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile      # <- this tells Render which Dockerfile to use
    buildFilterPath: ./actions/       # <- this sets build context to /actions/
