services:
  - type: web
    name: hr-backend
    env: python
    buildCommand: "pip install -r requirements.txt && rasa train"
    startCommand: "rasa run --enable-api --cors '*' --port 10000"
    plan: free
    envVars:
      - key: RASA_ENV
        value: production
    build:
      pythonVersion: 3.10  

  - type: web
    name: hr-actions
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile   
